edition = "2024";

package doctryne.inspection.v1;

option go_package = "github.com/domsnail/doctryne/api/gen/go/inspection/v1;inspection_v1";
option features.(pb.go).api_level = API_OPAQUE;
option features.field_presence = IMPLICIT;

//

import "google/protobuf/go_features.proto";

//

import "inspection/v1/inspection.proto";
import "utils/uuid.proto";

service InspectionService {
  rpc Inspect(InspectionOptions) returns (Inspection);

  rpc GetInspectionByUUID(utils.v1.UUID) returns (Inspection);
}