name: doctryne-staging

secrets:
  github-api-key:
    environment: GITHUB_API_KEY
  npm-api-key:
    environment: NPM_API_KEY
  stack-exchange-api-key:
    environment: STACK_EXCHANGE_API_KEY
  nvd-api-key:
    environment: NVD_API_KEY

services:
  database:
    image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/postgres:18.1-alpine
    hostname: database
    deploy:
      replicas: 1
      resources:
        reservations:
          memory: 32mb
          cpus: 2
        limits:
          memory: 512mb
          cpus: 4
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 30s
        delay: 10s
    stop_grace_period: 30s
    shm_size: 64mb
    environment:
      - POSTGRES_DB=staging
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    expose:
      - 5432
    volumes:
      - /opt/doctryne/staging/postgres:/var/lib/postgresql
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "staging", "-U", "${DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 3

  server:
    image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512mb
          cpus: 2
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 30s
        delay: 10s
    stop_grace_period: 30s
    secrets:
      - ghsa-api-key
      - npm-api-key
      - nvd-api-key
      - stack-exchange-api-key
    environment:
      # server configuration
      - SRV_ENABLED=true

      # database connection
      - DB_DRIVER=postgres
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=staging
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_TZ=Europe/Moscow

      # logging
      - LOG_LEVEL=-4
      - LOG_FORMAT=json

      # vulnerability database updates
      - DISABLE_AUTO_UPDATES=false
      - DISABLE_STARTUP_UPDATES=true

      # remote credentials
      - GITHUB_API_KEY=${GITHUB_API_KEY}
      - NPM_API_KEY=${NPM_API_KEY}
      - STACK_EXCHANGE_API_KEY=${STACK_EXCHANGE_API_KEY}
      - NVD_API_KEY=${NVD_API_KEY}
    expose:
      - 8080
    volumes:
      - /opt/doctryne/staging/postgres:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider --timeout=5 http://localhost:8080/health || exit 1" ]
      interval: 300s
      timeout: 5s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.doctryne-stage.service=doctryne-stage"
      - "traefik.http.routers.doctryne-stage.rule=Host(`doctryne-staging-01.domsnail.ru`)"
      - "traefik.http.routers.doctryne-stage.tls=true"
      - "traefik.http.routers.doctryne-stage.entrypoints=websec"
      - "traefik.http.services.doctryne-stage.loadbalancer.server.port=8080"
      - "traefik.http.routers.doctryne-stage.middlewares=doctryne-stage-auth@docker"
      - "traefik.http.middlewares.doctryne-stage-auth.basicauth.users=${HTTP_BASIC_PASS}"